### ISSUE TITLE
[FEATURE REQ] Azure configure API design

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1074]
```java
            Azure azure = Azure.configure()
                    .withLogOptions(new HttpLogOptions())
                    .authenticate(credFile)
                    .withDefaultSubscription();
```
The withLogOptions is not quite compatible with version 1. 
And its usage is not straightforward as other APIs.

**Comment by weidongxu-microsoft** [comment]
@yungezz @ChenTanyi @xccc-msft 

Plan to keep a similar interface of
```
.withLogLevel(HttpLogDetailLevel.BASIC)
```
(same method name, but use the new enum in core)

while maintain the `withLogOptions` interface
```
.withLogOptions(new HttpLogOptions())
```
since user might want to set `applicationId`.

And this requires a merge logic on `HttpLogOptions.logLevel` since it got 2 sources. Plan is which set last will be used.

There is other 2 setting of `allowedHeaderNames`, `allowedQueryParamNames`, which is just whitelist on what will be logged (other header/query will not be logged, I guess for security reason, no one want to have the `client_secret` in query or `Authenticate` in header get printed by default).

**Comment by yungezz** [comment]
thanks @weidongxu-microsoft  what's inside HttpLogOptions, sounds like LogLevel could be a property of LogOption

**Comment by weidongxu-microsoft** [comment]
@yungezz 
HttpLogOptions got 4. applicationId, logLevel, allowedHeaderNames, allowedQueryParamNames.

Currently the interface let use set HttpLogOptions. So if you want this, this issue is NOOP.

But usually user does not want to change all these. At least for us, we usually only change logLevel.

**Comment by yungezz** [comment]
thanks @weidongxu-microsoft . I fully agree to have a deligated set logLevel method as that's what used most normally. The design looks good. As for the merge logic, little concern it maybe little difficult for debug purpose if last set will be used, what do you think?
