### ISSUE TITLE
Azure Consumption list does NOT observe the Top parameter

### ISSUE THREAD

**Issue by ardias** [Azure/azure-libraries-for-java#184]
Hi,
When using `ConsumptionManagementClientImpl.list(final String scope, final String expand, final String filter, final String skiptoken, final Integer top)` to fetch usage data, when the **top** parameter is used to limit the number of results (for example 10) does not stop at the specified number or results, like the azure command line does, and keeps fetching data.
This seems to be because the client keeps following the **nextPageLink** that is returned in the first result without taking into consideration the previous number of results and the **top** parameter.

**Comment by hovsepm** [comment]
this seems to be AutoRest java codegen issue.

**Comment by RikkiGibson** [comment]
Hi @ardias, could you tell me which method on which class specifically has the issue, since ConsumptionManagementClientImpl itself does not have a `list` method?

For a short-term workaround to list a small number of items you may wish to try `listSinglePageAsync(...).toBlocking().single()`.

In our autogenerated code we don't have any special recognition of the `top` parameter --- we don't know that it refers to the total number of items the user wants in the paged list. So if the service continues to give us `nextPageLink` values all the PagedList knows how to do is follow the links.

A better solution to this may involve hand-authoring a wrapper around the generated code. Otherwise the service behavior will have to change so that if it has given all the items the user has asked for it should give a null `nextPageLink`.

**Comment by ardias** [comment]
BTW, I can limit the results using the filter, with start and end dates. The top parameter, for me at least, it not that important. I just noticed that it wasn't working as the AZ cli tool.

**Comment by RikkiGibson** [comment]
OK. Interesting behavior. Also wondering: is the client making requests using the same nextPageLink repeatedly or using the most recently received nextPageLink for each request?

**Comment by ardias** [comment]
I think it's using the one received from the response for each page, but I have to confirm it later since I'm not at the computer now.

**Comment by ardias** [comment]
Update: after looking at the code and a bit of debugging I can confirm that the client is using the nextPageLink that comes in the response for each request, ie, the most recent. Can also confirm that the **top** parameter is always included (and the **skiptoken** parameter value is different every time).

**Comment by RikkiGibson** [comment]
Thank you for looking into that. It seems like will be more than a bugfix on our side. Either the service behavior would need to change or we would need to manually wrap ConsumptionManagementClientImpl to gracefully handle the top parameter. Please let us know if the `listSinglePageAsync(...).toBlocking().single()` will be sufficient in the short term for your use case.

**Comment by ardias** [comment]
Sure no problem. For my use case I don't specifically need the top parameter, so I can live fine with the current implementation.
You can close the issue if you want.

**Comment by RikkiGibson** [comment]
Got it. Please reopen if you wish to follow up on this. 👍
