### ISSUE TITLE
Problem 1.15 - missing class - com/microsoft/azure/management/compute/implementation/ImageReferenceInner.class

### ISSUE THREAD

**Issue by renutz** [Azure/azure-libraries-for-java#594]
Trying to access imageReference() from vminstance.storageProfile().imageReference(), gives the error:

Oops: NoSuchMethodError
An unexpected error occured caused by exception NoSuchMethodError: com.microsoft.azure.management.compute.StorageProfile.imageReference()Lcom/microsoft/azure/management/compute/implementation/ImageReferenceInner;

On azure-mgmt-compute-1.15.1.jar there is no class ImageReferenceInner.class. On azure-mgmt-compute-1.8.0.jar, the class is there.

Please fix ASAP.

**Comment by anuchandy** [comment]
@renutz,  the return type of StorageProfile::imageReference() is [ImageReference](https://github.com/Azure/azure-libraries-for-java/blob/7f90b3ca624e338344a6dd8a28ddb41fc4fb2c92/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/StorageProfile.java#L51). ImageReferenceInner type present in early version of SDK due to an issue in codegen which we fixed and the new corresponding model is ImageReference

**Comment by renutz** [comment]
OK. Recompiling everything from the scratch worked. Thanks for the attention.
