### ISSUE TITLE
Is there DefaultAWSCredentialsProviderChain equivalent for loading AzureCredential? 

### ISSUE THREAD

**Issue by barryku** [Azure/azure-libraries-for-java#803]
**Query/Question**
We have integration tests that use ApplicationTokenCredentials to authenticate. It would be really nice if the default credentials can be loaded from ~/.aws folder, so developers don't need to modify a property file or something to enter their credentials.  AWS provides DefaultAWSCredentialsProviderChain does just that which makes it easy to manage unit tests.

**Comment by xccc-msft** [comment]
@barryku Hi, can you please check below link whether this is what you are looking for?
https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md#using-credentials-from-azure-cli-automatically-preview
If not, please share more details on how you use ApplicationTokenCredentials to authenticate currently. Thanks.

**Comment by xccc-msft** [comment]
Hi @barryku The AzureCliCredentials.create() will help load credentials from ~/.azure folder. To have this folder, you need to authenticate with Azure CLI first. For your requirement to manage unit tests, the suggestion is to authenticate with service principal so that the access token will never expire until the service principal credential expires.
